### ISSUE TITLE
Grouped plot hits the limit of 1000 and doesn't render with not-friendly exception

### ISSUE THREAD

**Issue by ileasile** [JetBrains/lets-plot#1224]
STR:
1. Take grouped plot with more than 1000 groups: https://gist.github.com/ileasile/ac784e78dcd4fd7ce0e5586352353897 (actual data is omitted)
2. Render it to HTML
```kotlin
PlotHtmlExport.buildHtmlFromRawSpecs(parsePlotSpec(spec), "")
```

Get the exception:

```
Figure spec kind is not defined.
java.lang.IllegalArgumentException: Figure spec kind is not defined.
	at org.jetbrains.letsPlot.core.spec.FigKind$Companion.fromOption(FigKind.kt:16)
	at org.jetbrains.letsPlot.core.spec.config.PlotConfig$Companion.figSpecKind(PlotConfig.kt:209)
	at org.jetbrains.letsPlot.core.spec.PlotConfigUtil.enumPlots(PlotConfigUtil.kt:66)
	at org.jetbrains.letsPlot.core.spec.PlotConfigUtil.findComputationMessages(PlotConfigUtil.kt:53)
	at org.jetbrains.letsPlot.core.util.PlotHtmlHelper.getStaticDisplayHtmlForRawSpec(PlotHtmlHelper.kt:208)
	at org.jetbrains.letsPlot.core.util.PlotHtmlExport.buildHtmlFromRawSpecs(PlotHtmlExport.kt:30)
	at org.jetbrains.letsPlot.core.util.PlotHtmlExport.buildHtmlFromRawSpecs$default(PlotHtmlExport.kt:22)
	at org.jetbrains.letsPlot.core.util.PlotHtmlExportTest.suPu(PlotHtmlExportTest.kt:80)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:54)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:53)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:92)
	at jdk.proxy1/jdk.proxy1.$Proxy4.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:183)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:132)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:103)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:63)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:121)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

```

When I run it in test, I get another, more meaningful exception:

```
ERROR SpecTransformBackendUtil - Internal error: IllegalStateException : Too many groups: 1070
```

I would expect two improvements here:
1. Propagate internal error message and fail fast
2. Make it possible to specify the limit or loosen it.

**Comment by alshan** [comment]
I don't quite get it. Do you have a use-case where 1070 groups or more is intentional/expected outcome?
