### ISSUE TITLE
PyCharm integration: Lets-Plot plugin is partially defunct on macOS.

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#276]
The last (6th) step of the [plugin's](https://plugins.jetbrains.com/plugin/14379-lets-plot-in-sciview) 'General Usage Instructions' doesn't show the plot. 

Instead, an error is shown in PyCharm console:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/dev-py37/lib/python3.7/site-packages/lets_plot/__init__.py", line 16, in <module>
    from .export import *
  File "/opt/anaconda3/envs/dev-py37/lib/python3.7/site-packages/lets_plot/export/__init__.py", line 4, in <module>
    from .ggsave_ import *
  File "/opt/anaconda3/envs/dev-py37/lib/python3.7/site-packages/lets_plot/export/ggsave_.py", line 8, in <module>
    from .simple import export_svg, export_html
  File "/opt/anaconda3/envs/dev-py37/lib/python3.7/site-packages/lets_plot/export/simple.py", line 8, in <module>
    from .. import _kbridge as kbr
  File "/opt/anaconda3/envs/dev-py37/lib/python3.7/site-packages/lets_plot/_kbridge.py", line 7, in <module>
    import lets_plot_kotlin_bridge
ImportError: dlopen(/opt/anaconda3/envs/dev-py37/lib/python3.7/site-packages/lets_plot_kotlin_bridge.cpython-37m-darwin.so, 2): Symbol not found: _NSGenericException
  Referenced from: /opt/anaconda3/envs/dev-py37/lib/python3.7/site-packages/lets_plot_kotlin_bridge.cpython-37m-darwin.so
  Expected in: flat namespace
 in /opt/anaconda3/envs/dev-py37/lib/python3.7/site-packages/lets_plot_kotlin_bridge.cpython-37m-darwin.so
```

Affected Lets-Plot versions: 1.5.3, 1.5.4, 1.5.5

**Comment by alshan** [comment]
The issue was fixed in Lets-Plot v1.5.6

by commit: https://github.com/JetBrains/lets-plot/commit/1cc4002241d3742c78f1a0cefd25943afd3194d2
