### ISSUE TITLE
windows-10 error ImportError: DLL load failed: 找不到指定的模块。

### ISSUE THREAD

**Issue by wangshangkun** [JetBrains/lets-plot#366]
`
Traceback (most recent call last):
  File "C:/Users/Admin/PycharmProjects/algorithm_practice/Pandas/les_lpot_test.py", line 7, in <module>
    from lets_plot import *
  File "C:\Users\Admin\PycharmProjects\algorithm_practice\venv\lib\site-packages\lets_plot\__init__.py", line 17, in <module>
    from .frontend_context import *
  File "C:\Users\Admin\PycharmProjects\algorithm_practice\venv\lib\site-packages\lets_plot\frontend_context\__init__.py", line 6, in <module>
    from ._configuration import *
  File "C:\Users\Admin\PycharmProjects\algorithm_practice\venv\lib\site-packages\lets_plot\frontend_context\_configuration.py", line 8, in <module>
    from ._html_contexts import _create_html_frontend_context, _use_isolated_frame
  File "C:\Users\Admin\PycharmProjects\algorithm_practice\venv\lib\site-packages\lets_plot\frontend_context\_html_contexts.py", line 7, in <module>
    from ._jupyter_notebook_ctx import JupyterNotebookContext
  File "C:\Users\Admin\PycharmProjects\algorithm_practice\venv\lib\site-packages\lets_plot\frontend_context\_jupyter_notebook_ctx.py", line 14, in <module>
    from .. import _kbridge as kbr
  File "C:\Users\Admin\PycharmProjects\algorithm_practice\venv\lib\site-packages\lets_plot\_kbridge.py", line 7, in <module>
    import lets_plot_kotlin_bridge
ImportError: DLL load failed: 找不到指定的模块。

Process finished with exit code 1

`

**Comment by VDovidaytis-HORIS** [comment]
Could you provide more details about your system, please?

 - Actual Windows 10 version ("This PC" - "Properties" - "About").
 - Python and Anaconda versions.
 - Lets-Plot version.

Also you can try to use the latest Lets-Plot version and install MinGW toolchain:

`conda install m2w64-toolchain`

https://github.com/JetBrains/lets-plot/blob/master/README_PYTHON.md#installation

https://pypi.org/project/lets-plot/

**Comment by davidgilbertson** [comment]
Hi, I get this same error. Windows 11. The help page says MinGW toolchain is required, but the link seems to assume I'm using conda, which I am not.

How does a windows/pip user use lets_plot?

**Comment by alshan** [comment]
Hi @davidgilbertson AFAIU you can use msys2 shell and `pacman` to install mingw along with python and pip on Windows. 
```
$ pacman -S mingw-w64-x86_64-python-pip
``` 
https://packages.msys2.org/package/mingw-w64-x86_64-python-pip

Then you can use `pip` for managing your python env.

I've never tried that though.
