### ISSUE TITLE
Not working in windows cmd prompt

### ISSUE THREAD

**Issue by antonio-yu** [JetBrains/lets-plot#456]
let's plot works well in pycharm and jupyter notebook. 
But when I try to run the script in cmd prompt, errors occour:
```
from lets_plot import *

D:\programfiles\anaconda\lib\site-packages\numpy\__init__.py:143: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\yuliang18\AppData\Roaming\Python\Python38\site-packages\lets_plot\__init__.py", line 17, in <module>
    from .frontend_context import *
  File "C:\Users\yuliang18\AppData\Roaming\Python\Python38\site-packages\lets_plot\frontend_context\__init__.py", line 6, in <module>
    from ._configuration import *
  File "C:\Users\yuliang18\AppData\Roaming\Python\Python38\site-packages\lets_plot\frontend_context\_configuration.py", line 8, in <module>
    from ._html_contexts import _create_html_frontend_context, _use_isolated_frame
  File "C:\Users\yuliang18\AppData\Roaming\Python\Python38\site-packages\lets_plot\frontend_context\_html_contexts.py", line 7, in <module>
    from ._jupyter_notebook_ctx import JupyterNotebookContext
  File "C:\Users\yuliang18\AppData\Roaming\Python\Python38\site-packages\lets_plot\frontend_context\_jupyter_notebook_ctx.py", line 14, in <module>
    from .. import _kbridge as kbr
  File "C:\Users\yuliang18\AppData\Roaming\Python\Python38\site-packages\lets_plot\_kbridge.py", line 7, in <module>
    import lets_plot_kotlin_bridge
ImportError: DLL load failed while importing lets_plot_kotlin_bridge: 找不到指定的模块。

```
Environment:

- win 64
- python 3.8.8
- lets plot  2.1 
- conda install m2w64-toolchain  : done

**Comment by VDovidaytis-HORIS** [comment]
Hello!

You seem to have two separate Python installations, one from the system default and one from the Anaconda environment. The `m2w64-toolchain`, which allows Lets-Plot and its dependencies to run normally on the Windows platform, is installed in the Anaconda environment. To check this, simply run the `conda activate` command in a command line session, then start Python with the `python` command and try `from lets_plot import *`.

The same solution for your VScode and RStudio: check your Python interpreter settings - they should point to Python from the Anaconda environment.

**Comment by antonio-yu** [comment]
@VDovidaytis-HORIS  @alshan 
Hello, thanks for replying and sorry for late feedback.
I checked and tested once more about the issues and solutions mentioned. 

1. Only one unique pyhon environments is installed ,e.g. Anaconda environment.
```
C:\Users\yuliang18>where python
D:\programfiles\anaconda\python.exe

C:\Users\yuliang18>conda info -e
# conda environments:
#
base                  *  D:\programfiles\anaconda

```
2.  `"C:\Users\yuliang18\AppData\Roaming\Python\Python38\site-packages"` seems to be the cached folders. I deleted the `...\AppData\Roaming\Python` folder and reinstall lets_plot, then run  `conda activate base` command in a command line session
first, after that I started `python` and tried `from lets_plot import *` ,  it went well. 
**Problems resolved in cmd prompt and VSCODE**

3.However , in Rsutdio , the same error still exists. 
The interpreter does point to the Python from the Anaconda environment (only anaconda environment is installed).
The Importerror happens when importing lets-plot,while other packages not.
Here is  the test code in Rstudio.

`
> reticulate::repl_python()
Python 3.8.8 (D:/programfiles/anaconda/python.exe)
Reticulate 1.22 REPL -- A Python interpreter in R.
Enter 'exit' or 'quit' to exit the REPL and return to R.
>>> import plotly.express as px 
>>> from lets_plot import * 
ImportError: DLL load failed while importing lets_plot_kotlin_bridge: 鎵句笉鍒版寚瀹氱殑妯″潡銆?
>>> import pandas as pd 
`

**Comment by antonio-yu** [comment]
I tried some measures to resolve the problem in Rstudio.

The existing error is  `ImportError: DLL load failed while importing lets_plot_kotlin_bridge` .
I found a python script named `lets_plot_kotlin_bridge.py` in  folder` Pycharm\python_stubs `, so I copied that script to 
folder `programfiles\anaconda\Lib` . 
The codes in lets_plot_kotlin_bridge.py are :
`
# encoding: utf-8
# module lets_plot_kotlin_bridge
# from D:\programfiles\anaconda\lib\site-packages\lets_plot_kotlin_bridge.cp38-win_amd64.pyd
# by generator 1.147
# no doc
# no imports

# functions

def export_html(*args, **kwargs): # real signature unknown
    """ Generates HTML page showing plot. """
    pass

def export_svg(*args, **kwargs): # real signature unknown
    """ Generates SVG representing plot. """
    pass

def generate_html(*args, **kwargs): # real signature unknown
    """ Generates HTML and JS sufficient for buidling of interactive plot. """
    pass

# no classes
# variables with complex values

__loader__ = None # (!) real value is '<_frozen_importlib_external.ExtensionFileLoader object at 0x000001DDAFCFF370>'

__spec__ = None # (!) real value is "ModuleSpec(name='lets_plot_kotlin_bridge', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x000001DDAFCFF370>, origin='D:\\\\programfiles\\\\anaconda\\\\lib\\\\site-packages\\\\lets_plot_kotlin_bridge.cp38-win_amd64.pyd')"

`

After that I retried the ploting codes in Rstudio, no  `ImportError` happened, but not plots showed either . The only result was 
`<lets_plot.plot.core.PlotSpec object at 0x00000267A65F58E0>`

`
import numpy as np
from lets_plot import *
LetsPlot.setup_html()
x = np.linspace(-2 * np.pi, 2 * np.pi, 100)
y = np.sin(x)
ggplot({'x': x, 'y': y}, aes(x='x', y='y')) + geom_point()

<lets_plot.plot.core.PlotSpec object at 0x00000267A65F58E0>
`
If I stored the plot by a variable, it returned another result:  `{'text/html': None} `

`
...
p=ggplot({'x': x, 'y': y}, aes(x='x', y='y')) + geom_point()
p.show()

{'text/html': None}
`

**Comment by antonio-yu** [comment]
I wanna share `lets_plot`  with my colleges. 
Rmarkdown can very efficient,in which, the codes and plots show together in a html document.
If lets_plot doesn't work in Rstudio, it would be a pity. 

So, @alshan @VDovidaytis-HORIS ,I wish this issue could be fixed.

**Comment by antonio-yu** [comment]
Hello, @alshan 
Thanks for you reply. Importing issue solved.
I tried  
```
> from IPython.display import display, HTML
> display(HTML("<h1>Hello!</h1>"))
```
in Rstudio, I didn't render the `Hello!  `as  other Python IDE did. So I guess  Rstudio can't make it come true at the moment.
