### ISSUE TITLE
`scaleColorManual` Divide by Zero with 1 mapping

### ISSUE THREAD

**Issue by ccjernigan** [JetBrains/lets-plot#506]
STEPS TO REPRODUCE
1. Configure a plot with scaleColorManual with a single mapping, e.g. 

        scaleColorManual(
            values = listOf("blue"),
            labels = listOf("mylabel")
        )

2. Try to graph the data

RESULTS
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at jetbrains.datalore.plot.base.scale.Mappers$DiscreteFun.apply(Mappers.kt:129)
	at jetbrains.datalore.plot.base.scale.Mappers$discrete$1.invoke(Mappers.kt:97)
	at jetbrains.datalore.plot.base.scale.Mappers$discrete$1.invoke(Mappers.kt:97)
	at jetbrains.datalore.plot.builder.scale.mapper.GuideMapperWithGuideBreaks.apply(GuideMapperWithGuideBreaks.kt:21)
	at jetbrains.datalore.plot.builder.scale.mapper.GuideMapperWithGuideBreaks.apply(GuideMapperWithGuideBreaks.kt:11)
	at jetbrains.datalore.plot.builder.scale.ScaleProviderBuilder$MyScaleProvider$createScale$mapper$1.invoke(ScaleProviderBuilder.kt:175)
	at jetbrains.datalore.plot.builder.scale.ScaleProviderBuilder$MyScaleProvider$createScale$mapper$1.invoke(ScaleProviderBuilder.kt:175)
	at jetbrains.datalore.plot.base.scale.ScaleUtil.map(ScaleUtil.kt:29)
	at jetbrains.datalore.plot.builder.assemble.LegendAssembler$LegendLayer.<init>(LegendAssembler.kt:135)
	at jetbrains.datalore.plot.builder.assemble.LegendAssembler.addLayer(LegendAssembler.kt:43)
	at jetbrains.datalore.plot.builder.assemble.PlotAssemblerUtil.createLegends(PlotAssemblerUtil.kt:182)
	at jetbrains.datalore.plot.builder.assemble.PlotAssemblerUtil.createLegends(PlotAssemblerUtil.kt:110)
	at jetbrains.datalore.plot.builder.assemble.PlotAssembler.createPlot(PlotAssembler.kt:46)
	at jetbrains.datalore.plot.MonolithicCommon.buildSvgImagesFromRawSpecs(MonolithicCommon.kt:48)
	at jetbrains.datalore.plot.PlotSvgExportPortable.buildSvgImageFromRawSpecs(PlotSvgExportPortable.kt:42)
	at jetbrains.datalore.plot.PlotSvgExport.buildSvgImageFromRawSpecs(PlotSvgExport.kt:25)
	at jetbrains.datalore.plot.PlotSvgExport.buildSvgImageFromRawSpecs$default(PlotSvgExport.kt:21)
	at jetbrains.datalore.plot.PlotImageExport.buildImageFromRawSpecs(PlotImageExport.kt:90)
	at jetbrains.letsPlot.export.GgsaveKt.exportRasterImage(ggsave.kt:122)
	at jetbrains.letsPlot.export.GgsaveKt.ggsave(ggsave.kt:88)

**Comment by alshan** [comment]
Fixed in [v3.2.0](https://github.com/JetBrains/lets-plot-kotlin#what-is-new-in-320)
